### ISSUE TITLE
Inappropriate semicolon in PHP-modus

### ISSUE THREAD

**Issue by ReneFroger** [emacs-berlin/syntactic-close#10]
Hi there! It's me again. 

`[]` stands for the cursor. 
Consider the following, while in PHP-mode: 

```
if ($foobar){
    foreach ($foobar as $key =>  $val) {
         echo $key;[]
```

When I call `general-close` twice, he places the closing bracket twice with the right indentation. Perfectly. :smiley:.

However, when the cursor is on a line below, like: 

```
if ($foobar){
    foreach ($foobar as $key =>  $val) ;{
         echo $key;
         []
```

When I call `general-close`, he will put a semicolon instead putting a closing bracket. When I call `general-close` again but twice, there are the closing brackets twices right on the indendation. But the semicolon doesn't belong there. 

I also noticed that `general-close-stack-based` is doing this job right, without placing the semicolon there. But it lacks the indendation, like in `general-close`. So I'm wondering what the difference between `general-close-stack-based` and `general-close` is? :frowning:.

Any way to get the right behaviour of `general-close-stack-based` in the case of the unneccesary semicolon, but with the auto indentation of `general-close`?

**Comment by andreas-roehler** [comment]
> I also noticed that |general-close-stack-based| is doing this job 
> right, without placing the semicolon there. But it lacks the 
> indendation, like in |general-close|. So I'm wondering what the 
> difference between |general-close-stack-based| and |general-close| is.

The stack-based code doesn't care for a semicolon at all.

It's kept mainly for historical reasons, representing the first approach 
as a result of a community hack. Was replaced by a parse-partial-sexp 
based solution.

BTW: stack-based would work also inside comment and string.

> Any way to get the right behaviour of |general-close-stack-based| in 
> the case of the unneccesary semicolon, but with the auto indentation 
> of |general-close|?

**Comment by andreas-roehler** [comment]
Am 30.06.2015 um 22:59 schrieb ReneFroger:

> Hi there! It's me again.
> 
> [] = cursor.
> Consider the following:
> 
> |if ($foobar){
>      foreach ($foobar as $key =>  $val) {
>           echo $key;[]
> |
> 
> When I call |general-close| twice, he places the closing bracket twice 
> with the right indentation. Perfectly. :smiley:.
> 
> However, when the cursor is on a line below, like:
> 
> |if ($foobar){
>      foreach ($foobar as $key =>  $val) ;{
>           echo $key;
>           []
> |

Hmm, is this valid php? What an empty list here is expected to result?

**Comment by andreas-roehler** [comment]
Am 30.06.2015 um 22:59 schrieb ReneFroger:

> Hi there! It's me again.
> 
> [] = cursor.
> Consider the following:
> 
> |if ($foobar){
>      foreach ($foobar as $key =>  $val) {
>           echo $key;[]
> |
> 
> When I call |general-close| twice, he places the closing bracket twice 
> with the right indentation. Perfectly. :smiley:.
> 
> However, when the cursor is on a line below, like:
> 
> |if ($foobar){
>      foreach ($foobar as $key =>  $val) ;{
>           echo $key;
>           []
> |
> 
> When I call |general-close|, he will put a semicolon instead putting a 
> closing bracket. When I call |general-close| again but twice, there 
> are the closing brackets twices right on the indendation. But the 
> semicolon doesn't belong there.
> 
> I also noticed that |general-close-stack-based| is doing this job 
> right, without placing the semicolon there. But it lacks the 
> indendation, like in |general-close|. So I'm wondering what the 
> difference between |general-close-stack-based| and |general-close| is.
> 
> Any way to get the right behaviour of |general-close-stack-based| in 
> the case of the unneccesary semicolon, but with the auto indentation 
> of |general-close|?

Okay, see the issue. Mistook the "[]" :)

**Comment by ReneFroger** [comment]
Works like a charm! Thank you, Andreas! :dancers:.
