### ISSUE TITLE
Defunct PHP Mode for Testing

### ISSUE THREAD

**Issue by ejmr** [emacs-berlin/syntactic-close#15]
The version of PHP Mode used in the project is very out of date.  Personally I think you should use [the current version](https://github.com/ejmr/php-mode) just in case some of the work we've done with handling syntax in PHP Mode causes problems with general-close.

**Comment by andreas-roehler** [comment]
Thanks. If someone updates the travis-script accordingly, we may drop shipping  a copy.

**Comment by andreas-roehler** [comment]
Hi Andreas, hope it's okay for you.

**Comment by pxlpnk** [comment]
I will take a look as soon as I have some spare time. Might not be before first week of August though.
We could give it a try next week in the meetup. What do you think @andreas-roehler

**Comment by ejmr** [comment]
As the maintainer of PHP Mode, please let me know if there's anything I can do to help with this, or with anything in regard to general-close working with PHP code.

**Comment by andreas-roehler** [comment]
Am 24.07.2015 um 15:41 schrieb Andreas Tiefenthaler:

> I will take a look as soon as I have some spare time. Might not be 
> before first week of August though.
> We could give it a try next week in the meetup. What do you think 
> @andreas-roehler https://github.com/andreas-roehler
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/emacs-berlin/general-close/issues/15#issuecomment-124524423.

Great, thanks!

**Comment by andreas-roehler** [comment]
Came across php-mode, done.
