### ISSUE TITLE
General close not on MELPA?

### ISSUE THREAD

**Issue by ReneFroger** [emacs-berlin/syntactic-close#2]
Hi, thanks for sharing this package! Could this perhaps be listed on MELPA?

Thanks in advance!

**Comment by andreas-roehler** [comment]
Will take this as a compliment. Let's wait until support for the major languages is there.

**Comment by andreas-roehler** [comment]
As some more requests arrived, in progress now.

**Comment by andreas-roehler** [comment]
https://github.com/milkypostman/melpa/pull/2958

**Comment by pxlpnk** [comment]
we might want to think of having releases? What do you think @andreas-roehler ?

**Comment by ReneFroger** [comment]
Thanks for letting me know, @andreas-roehler.

**Comment by andreas-roehler** [comment]
Am 24.07.2015 um 11:17 schrieb Andreas Tiefenthaler:

> we might want to think of having releases? What do you think 
> @andreas-roehler https://github.com/andreas-roehler ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/emacs-berlin/general-close/issues/2#issuecomment-124452382.

Would welcome that. May you care for?

Want to silence a couple of compiler-warnings still - keeping a 
feature-freeze.

Cheers,

Andreas

**Comment by pxlpnk** [comment]
Sure, do we want to use semantic versioning and something like a changelog to keep track of changes?

**Comment by andreas-roehler** [comment]
Am 24.07.2015 um 15:42 schrieb Andreas Tiefenthaler:

> Sure, do we want to use semantic versioning and something like a 
> changelog to keep track of changes?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/emacs-berlin/general-close/issues/2#issuecomment-124524914.

Would welcome some kind of semantic versioning.

IMO it's good to have a NEWS file. Also at a first release? - don't know.

**Comment by pxlpnk** [comment]
I am in general a fan of the combination of:
http://keepachangelog.com/
and http://semver.org/

A news file would work too, but a changelog file is more common in the dev worlds I move around.

**Comment by andreas-roehler** [comment]
Am 24.07.2015 um 17:12 schrieb Andreas Tiefenthaler:

> I am in general a fan of the combination of:
> http://keepachangelog.com/
> and http://semver.org/
> 
> A news file would work too, but a changelog file is more common in the 
> dev worlds I move around.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/emacs-berlin/general-close/issues/2#issuecomment-124554820.

Interesting. Please go on as it's convenient for you.

AFAIU a NEWS file is mainly about features and related changes, while a 
changelog is symbol-oriented  - that way important for hackers.

**Comment by andreas-roehler** [comment]
https://github.com/milkypostman/melpa/pull/2958

Done
