### ISSUE TITLE
General close inside web-mode

### ISSUE THREAD

**Issue by ReneFroger** [emacs-berlin/syntactic-close#23]
This issue might be related: https://github.com/emacs-berlin/general-close/issues/4

For example, I have the following snippet

```
$(document).ready(function() {
    var test = 0 []
```

`[]` stands for the cursor.

Let assume the above snippet is in JS2-mode.
When I call `general-close`, it will insert `;`, then `}`, and finally `);`.

But what if the buffer is in the [web-mode](http://web-mode.org/)?

Then you have the following in HTML file.

```
<script>
    $(document).ready(function() {
        var test = 0 []
</script>
```

When I'm calling `general-close`, the bracket `}`, and parenthese `)` are
inserted, but no semicolon. So I was wondering if this could be possible?

Note that you could check which part of the HTML file is Javascript and which
part is HTML, with for example

```
 (if (string= (web-mode-language-at-pos) "html")
 Do something here
```

**Comment by andreas-roehler** [comment]
Behavior is directed by contents of variable "major-mode". Listing web-mode in general-close--semicolon-separator-modes is needed.

BTW fixed a bug WRT php at the occassion.

**Comment by ReneFroger** [comment]
Thank you! Your support here is awesome. :+1:

**Comment by andreas-roehler** [comment]
Just seeing commit-message got the wrong ticket-number. Anyone serious about that? Lets pass that way - not a big enterprise yet :)

**Comment by ReneFroger** [comment]
Noticed it, but nobody will care I guess. I'm already happy with your fix. :smile:.
