### ISSUE TITLE
Simple Mode

### ISSUE THREAD

**Issue by runekaagaard** [emacs-berlin/syntactic-close#29]
Hi

Thanks for a great package. Is there an easy way to only have support for `"'[({` in all modes and not all the other stuff, like `:` in python?

**Comment by andreas-roehler** [comment]
On 04.07.2016 11:22, runekaagaard wrote:

> Hi
> 
> Thanks for a great package. Is there an easy way to only have support 
> for |"'[({| in all modes and not all the other stuff, like `:´ in python?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/emacs-berlin/general-close/issues/29, or mute the 
> thread 
> https://github.com/notifications/unsubscribe/ABHmk4OQ2goINwHTDj0RpDw3ey9tWlFqks5qSNDOgaJpZM4JEMg9.

Might be a suitable task for some live-hack.

As the command provides it already: May you tell the use-case for the 
request? Resp. does anything from current implementation go into your way?

Cheers,

Andreas

**Comment by andreas-roehler** [comment]
parse-partial-sexp returns a list

With that result (nth 1 LIST) is the start-position of innermost list

(save-excursion
(goto-char (nth 1 ...

Look which char that is, resp. select the closing complement and insert 
at original place.

**Comment by runekaagaard** [comment]
Hi Andreas

It does work a bit funky in web-mode on .jsx files, but for me, my favorite usecase would be just the brackets and quotes, even if it worked perfectly in all modes :). Will look into `parse-partial-sexp` thing, Thx!
