### ISSUE TITLE
Ability to add a semicolon? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-berlin/syntactic-close#3]
Hi there! I got hinted from Andreas that I could use this plugin. This plugin is nearly perfect. Only one thingy I am missing. 

For example, like in PHP, you have the following

```
 public function Foobar()
 {
     echo "Foobar
```

So when I will call general close, he will close the double quote (`"`), missing in order to close the string "Foobar", but he will not close then with a semicolon (`;`) to end the line. But he will close it with a bracket (`}`) to close the function Foobar. 

I was wondering if general-close could use a semicolon (`;`), (I use [PHP-mode](https://github.com/ejmr/php-mode) by the way). When I looked in the source code of general close, I noticed he will check for the open signs (like `{`, `[`, `(`). But the problem is that there is no correspodenting sign for the semicolon. Then I assume we need to invent something. 

So I'm wondering if there is a way to have magic powers in this case?

**Comment by andreas-roehler** [comment]
Am 19.06.2015 um 17:38 schrieb ReneFroger:

> |public function Foobar(){
> 
>   echo "Foobar|

Did you check out current trunk?

For now it results in

public function Foobar(){
   echo "Foobar"};

which is wrong AFAIK.

Would the following be right?:

public function Foobar(){
   echo "Foobar";
}

**Comment by ReneFroger** [comment]
Hi Andreas, thanks for your reply. The latter one like this: 

```
public function Foobar() {
   echo "Foobar";
}
```

would be indeed right. But I'll be curious how the script could figure out if there should be a semicolon placed. Especially not when it's ending with a double quote. Want sometimes you have the following situation:

```
public function Foobar() {
   echo $foo->bar();
}
```

So a closing semicolon could be happen on different cases. I have looked it upon Emacs documentation, if there something like this exists, that checks for the closing tags. But without luck.

**Comment by andreas-roehler** [comment]
Tests succeed interactively, but fail in batch mode. Any idea? Fix is committed, close that for now.

**Comment by ReneFroger** [comment]
Andreas, it works great here. I don't know why you have a fail in batch mode, but I loaded it in Emacs, both general-close.el and general-close-modes.el, and tested it, it works fine. Thanks for the great job! 
However, for private functions and protected functions it will not work. 

But when looking in the source code, I don't think it would be hard for me to change it. Thanks anyway!

**Comment by andreas-roehler** [comment]
Am 19.06.2015 um 20:11 schrieb ReneFroger:

> Andreas, it works great here. I don't know why you have a fail in 
> batch mode, but I loaded it in Emacs, both general-close.el and 
> general-close-modes.el, and tested it, it works fine. However, for 
> private functions and protected functions it will not work.
> 
> But when looking in the source code, I don't think it would be hard 
> for me to change it. Thanks anyway!
> 
> —

Please open a new ticket and provide some example code for the remaining 
issues.
So it will be fixed for others too.

Thanks,

Andreas

**Comment by ReneFroger** [comment]
I was wrong, it was a faulty setting in my Emacs configuration. After inspecting it, everything is working fine. 

Thanks for the help, it's really appreciated!

**Comment by andreas-roehler** [comment]
Am 19.06.2015 um 22:18 schrieb ReneFroger:

> I was wrong, it was a faulty setting in my Emacs configuration. 
> Everything is working fine.
> 
> Thanks for the help, it's really appreciated!
> 
> —

You are welcome!
