### ISSUE TITLE
Close Org Mode  "+BEGIN"-Expressions

### ISSUE THREAD

**Issue by publicimageltd** [emacs-berlin/syntactic-close#33]
Would it be too hard to add org mode's "+BEGIN_QUOTE", "+BEGIN_VERSE", "+BEGIN_EXAMPLE" and "+BEGIN_SRC" to syntactic close? (Akin to C-] in latex-mode, when closing environments) So that would add a corresponding "+END_SRC", "+END_QUOTE", etc.

**Comment by andreas-roehler** [comment]
Does these markups nest?

**Comment by publicimageltd** [comment]
No, they do not nest. The idea is just to generalize the logic of "closing something".

**Comment by andreas-roehler** [comment]
Done

**Comment by publicimageltd** [comment]
Thanks for the fast implementation, but it does not work yet. Looking at the code, the error seems to be the following part of the function ```syntactic-close-modes```:

      (`org-mode
       (setq done (syntactic-close-emacs-lisp-close closer pps t)))

Seems like the closing function never gets called.

Shouldn't it select "syntactic-close--org-mode-close" instead? Simply replacing the value didn't work, though.

**Comment by andreas-roehler** [comment]
Markup and regexp are wrong. Requires #+BEGIN_SRC, now +BEGIN_SRC.

**Comment by andreas-roehler** [comment]
Fixed
