### ISSUE TITLE
Trouble with markdown

### ISSUE THREAD

**Issue by To1ne** [emacs-berlin/syntactic-close#34]
When I use `syntactic-close` with markdown-mode, the cursor jumps to beginning of line.

Other than that it works fine for `{`, `(`, and `[`.

I haven't had time to look in to it more deeply, but I was wondering if others also suffered from this problem.

**Comment by andreas-roehler** [comment]
Thanks for the report.

**Comment by To1ne** [comment]
Wow, that's quick!! Huge thanks!!
