### ISSUE TITLE
do block in ruby not always closed correctly

### ISSUE THREAD

**Issue by To1ne** [emacs-berlin/syntactic-close#35]
Lately I'm having some trouble with syntactic-close with ruby `do ... end` blocks.

### Good

```ruby
def toon<-- cursor here
```

```ruby
while 1 do<-- cursor here
```

### Bad

```ruby
it 'is' do<-- cursor here
```
It should add `end`, but instead it adds `,`.

**Comment by andreas-roehler** [comment]
Checked in some fix. Please again. Thanks reporting.

**Comment by andreas-roehler** [comment]
Please re-open if not done.
