### ISSUE TITLE
avoid major-mode switching after insertion.

### ISSUE THREAD

**Issue by amosbird** [emacs-berlin/syntactic-close#36]
When using `evil` together with `syntactic-close`, inserting a closing pair in `evil-insert-mode` somehow triggers a major-mode switching, which in turn leads to a evil-state change. Is there a way to avoid this? Thanks.

**Comment by andreas-roehler** [comment]
AFAIK syntactic-close doesn't set any major-mode. Assume its something from evil-mode responsable. Maybe provide some example starting from emacs -Q alongside with the state as shown by report-emacs-bug.

**Comment by amosbird** [comment]
see `syntactic-close.el:537`. It temporarily switches to `sgml-mode`.

**Comment by amosbird** [comment]
this seems to be a proper way to work around it.

```
(defun +amos-close-block ()
  (interactive)
  (evil-with-state 'insert
    (syntactic-close)))
```

**Comment by andreas-roehler** [comment]
Okay, see it. That shouldn't happen, thanks reporting.

**Comment by andreas-roehler** [comment]
Should  be fixed now.
