### ISSUE TITLE
Semicolon support for Javascript? 

### ISSUE THREAD

**Issue by ReneFroger** [emacs-berlin/syntactic-close#4]
In addition to the previous issue (https://github.com/emacs-berlin/general-close/issues/3), the ability to add a semicolon for PHP-mode was added, which I fell in love with it. I really appreciate your support in this. :smiley: 

Now when I use `general-close` for Javascript (with JS2-mode), I'm already missing the semicolon. 

For example, the structure could look like this: 

```
      $(document).ready(function() {

          $('.nav-tabs-custom-2').tabs();

          $('.table').delegate('td','mouseover mouseleave',function(e) {
              if (e.type == 'mouseover') {
                  $(this).addClass('hover');
              }
          });
        });
```

So I'm wondering if it's perhaps an option to add support for Javascript, if that's not too much to ask? :frowning:...

Thanks in advance for your reply.

**Comment by andreas-roehler** [comment]
Am 22.06.2015 um 23:14 schrieb ReneFroger:

> In addition to the previous issue (#3 
> https://github.com/emacs-berlin/general-close/issues/3), the ability 
> to add a semicolon for PHP-mode was added, which I fell in love with 
> it. I really appreciate your support in this. :smiley:
> 
> Now when I use |general-close| for Javascript (with JS2-mode), I'm 
> already missing the semicolon.
> 
> For example, the structure could look like this:
> 
> |       $(document).ready(function() {
> 
> ```
>        $('.nav-tabs-custom-2').tabs();
> 
>        $('.table').delegate('td','mouseover mouseleave',function(e) {
>            if (e.type == 'mouseover') {
>                $(this).addClass('hover');
>            }
>        });
>      });
> ```
> 
> |
> |
> 
> So I'm wondering if it's perhaps an option to add support for 
> Javascript, if that's not too much to ask? :frowning:...
> 
> Thanks in advance for your reply.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/emacs-berlin/general-close/issues/4.

Thanks for the request. Will look for it ASAP.

While reflecting a solution: what about reverting the proceeding in 
such: instead of implementing it mode by mode, shifting that 
command-separator-char insertion into the general part and switch it off 
if not convenient?

And have a (defcustom command-separator-char ";").

**Comment by ReneFroger** [comment]
Thanks for your reply. 

It would be an option, indeed. But I'm using it mainly for PHP and Javascript, so I don't think I will ever need it for another mode (I work with HTML and CSS too, and as far I know, they don't rely heavily on brackets and parentheses).

**Comment by andreas-roehler** [comment]
Code might need some cleanup still, but should work.
