### ISSUE TITLE
Adding the C-family of languages

### ISSUE THREAD

**Issue by appetrosyan** [emacs-berlin/syntactic-close#40]
Hi!

Very interesting plugin, hopefully will be incorporated into emacs directly one day. 

On that note, would it be possible to add official support for the C-family of languages? I don't think that separating them out would be necessary: as Java, Rust, Go and many others have extremely similar semantics in terms of where the delimiters could be (and should be) closed.

**Comment by andreas-roehler** [comment]
Hi, 
the mode is designed as a generic one. Need cases which fail in a specific language mode in order to support it.
